### ISSUE TITLE
我的服务器是亚马逊的在美国，导致连接不上openvpn应该怎么办，服务器不在国内

### ISSUE THREAD

**Issue by Woner1** [nieaowei/campus-network-unlock#10]
![image](https://user-images.githubusercontent.com/24207130/96704062-30510300-13c6-11eb-875a-5f290b60c0d7.png)

**Comment by Woner1** [comment]
这个是我的日志
![image](https://user-images.githubusercontent.com/24207130/96704193-5e364780-13c6-11eb-84e4-0130c3ac1d78.png)

**Comment by busiqiao** [comment]
+1 国外的服务器怎么搞

**Comment by nieaowei** [comment]
> 这个是我的日志
> ![image](https://user-images.githubusercontent.com/24207130/96704193-5e364780-13c6-11eb-84e4-0130c3ac1d78.png)



> +1 国外的服务器怎么搞

你们需要确认国内是否可以访问你的服务器IP（有没有被墙），然后确认服务器提供商的防火墙是否开放端口
