### ISSUE TITLE
如何在服务器控制上网时段呢？比如晚上9.00-10.00不允许连接

### ISSUE THREAD

**Issue by a1023182899** [nieaowei/campus-network-unlock#9]
如何在服务器控制上网时段呢？比如晚上9.00-10.00不允许连接

**Comment by nieaowei** [comment]
可以 ，由于课程较多临近期末，目前暂不考虑维护该项目，有需要可自行探索。

**Comment by a1023182899** [comment]
已经解决，用的是linux的crontab命令




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nieaowei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上9:07
收件人:&nbsp;"nieaowei/campus_network_unlock"<campus_network_unlock@noreply.github.com&gt;;
抄送:&nbsp;"花開 、〆 | "<1023182899@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nieaowei/campus_network_unlock] 如何在服务器控制上网时段呢？比如晚上9.00-10.00不允许连接 (#9)




可以 ，由于课程较多临近期末，目前暂不考虑维护该项目，有需要可自行探索。
